### ISSUE TITLE
Show download speed

### ISSUE THREAD

**Issue by gudarzi** [gudarzi/SaveHere#17]
The app must show current/average download speed to the user.
Also, use better units in frontend for showing file sizes!

**Comment by clementcampagna** [comment]
Hi @gudarzi 
I think this issue can be closed if  you're happy with the latest changes ;-)

**Comment by gudarzi** [comment]
Hi @clementcampagna 
I will add `average download speed` and then close this issue.

**Comment by clementcampagna** [comment]
Correct, I didn't add it yesterday. Let me know if you need any help!
