### ISSUE TITLE
Fix file name of downloaded files

### ISSUE THREAD

**Issue by gudarzi** [gudarzi/SaveHere#2]
Add an option for using filenames that the target server sends, instead of using the url which can end up creating files with invalid names!

**Comment by Sakunam** [comment]
Hi, I'd like to attempt this

**Comment by gudarzi** [comment]
@Sakunam It's great to hear you're interested in contributing. I look forward to your pull requests. Happy coding!

**Comment by clementcampagna** [comment]
Hi, I had a go at the issue.
Please let me know if you have any questions.
