### ISSUE TITLE
Add an option for using proxy servers

### ISSUE THREAD

**Issue by gudarzi** [gudarzi/SaveHere#31]
Add an option for using proxy servers for downloading files
This helps with accessing region-blocked files, proxy-protected files, etc.

**Comment by napalmCore** [comment]
hi, @gudarzi  Can i take this one?

**Comment by gudarzi** [comment]
@napalmCore Yes, of course. Also, since you're at it, could you please try implementing the video streaming thing for downloaded files as well?

**Comment by napalmCore** [comment]
@gudarzi sure!
