### ISSUE TITLE
Add input sanitization

### ISSUE THREAD

**Issue by gudarzi** [gudarzi/SaveHere#7]
There's no input sanitization. The app might be vulnerable to malicious user inputs.

Also, there are no checks on the downloaded files. Requested files could probably overwrite sensitive files on the host!

**Comment by dhrisyadas** [comment]
Hi would love to start my contributions for the first time from this issue. Could you pls tell me whether this issue can still worked on?

**Comment by gudarzi** [comment]
@dhrisyadas Hello! It's great to hear you're interested in contributing. Yes, this issue is still open for contributions. I appreciate your effort and look forward to your pull requests. Happy coding!
